// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SklepSDUKW.DAL;

#nullable disable

namespace SklepSDUKW.Migrations
{
    [DbContext(typeof(FilmsContext))]
    partial class FilmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SklepSDUKW.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Straszne filmy pełne napięcia, grozy i nadprzyrodzonych zjawisk.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Filmy science fiction osadzone w przyszłości, kosmosie lub alternatywnej rzeczywistości.",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Lekkie i humorystyczne produkcje mające na celu rozbawić widza.",
                            Name = "Komedia"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "Poruszające historie skupiające się na emocjach, relacjach i życiowych dylematach bohaterów.",
                            Name = "Dramat"
                        },
                        new
                        {
                            Id = 5,
                            Desc = "Dynamiczne filmy z widowiskowymi scenami walki, pościgów i efektów specjalnych.",
                            Name = "Akcja"
                        },
                        new
                        {
                            Id = 6,
                            Desc = "Filmy tworzone techniką animacji, skierowane zarówno do dzieci, jak i dorosłych.",
                            Name = "Animacja"
                        });
                });

            modelBuilder.Entity("SklepSDUKW.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Desc = "Historia rodziny nawiedzanej przez demoniczną obecność.",
                            Director = "James Wan",
                            Title = "The Conjuring"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Desc = "Psychologiczny horror o rodzinnej traumie i mrocznych tajemnicach.",
                            Director = "Ari Aster",
                            Title = "Hereditary"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Desc = "Klasyczna opowieść o opętaniu i egzorcyzmach.",
                            Director = "William Friedkin",
                            Title = "The Exorcist"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Desc = "Grupa dzieci stawia czoła przerażającemu klaunowi.",
                            Director = "Andy Muschietti",
                            Title = "It"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Desc = "Dziennikarka bada tajemniczą kasetę wideo przynoszącą śmierć.",
                            Director = "Gore Verbinski",
                            Title = "The Ring"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Desc = "Morderca atakujący swoje ofiary w snach.",
                            Director = "Wes Craven",
                            Title = "A Nightmare on Elm Street"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Desc = "Izolacja w hotelu prowadzi do szaleństwa.",
                            Director = "Stanley Kubrick",
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Desc = "Rodzina walczy z bytami z innego wymiaru.",
                            Director = "James Wan",
                            Title = "Insidious"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Desc = "Matka i syn konfrontują się z mroczną istotą z książki.",
                            Director = "Jennifer Kent",
                            Title = "The Babadook"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Desc = "Psychopatyczny morderca zmusza ofiary do makabrycznych wyborów.",
                            Director = "James Wan",
                            Title = "Saw"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Desc = "Podróż przez kosmos w poszukiwaniu nowego domu dla ludzkości.",
                            Director = "Christopher Nolan",
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Desc = "Złodzieje wnikają w sny, by kraść tajemnice.",
                            Director = "Christopher Nolan",
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Desc = "Haker odkrywa prawdziwą naturę rzeczywistości.",
                            Director = "The Wachowskis",
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Desc = "Łowca androidów odkrywa sekret zagrażający światu.",
                            Director = "Denis Villeneuve",
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Desc = "Lingwistka próbuje porozumieć się z obcą cywilizacją.",
                            Director = "Denis Villeneuve",
                            Title = "Arrival"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Desc = "Walka o kontrolę nad pustynną planetą Arrakis.",
                            Director = "Denis Villeneuve",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Desc = "Astronauci walczą o przetrwanie w przestrzeni kosmicznej.",
                            Director = "Alfonso Cuarón",
                            Title = "Gravity"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Desc = "Eksperyment z zaawansowaną sztuczną inteligencją.",
                            Director = "Alex Garland",
                            Title = "Ex Machina"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Desc = "Astronauta próbuje przeżyć samotnie na Marsie.",
                            Director = "Ridley Scott",
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Desc = "Podzielony świat przyszłości i walka o równość.",
                            Director = "Neill Blomkamp",
                            Title = "Elysium"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Desc = "Szalone poszukiwania zaginionego pana młodego w Las Vegas.",
                            Director = "Todd Phillips",
                            Title = "The Hangover"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Desc = "Dwóch nastolatków przeżywa ostatnią imprezę przed studiami.",
                            Director = "Greg Mottola",
                            Title = "Superbad"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Desc = "Mężczyzna przeżywa wciąż ten sam dzień.",
                            Director = "Harold Ramis",
                            Title = "Groundhog Day"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Desc = "Antybohater o niewyparzonym języku szuka zemsty.",
                            Director = "Tim Miller",
                            Title = "Deadpool"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Desc = "Seria katastrof podczas organizacji ślubu przyjaciółki.",
                            Director = "Paul Feig",
                            Title = "Bridesmaids"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Desc = "Nieśmiały mężczyzna odkrywa magiczną maskę.",
                            Director = "Chuck Russell",
                            Title = "The Mask"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Desc = "Chłopiec sam broni domu przed złodziejami.",
                            Director = "Chris Columbus",
                            Title = "Home Alone"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Desc = "Dwóch dorosłych mężczyzn musi nauczyć się wspólnego życia.",
                            Director = "Adam McKay",
                            Title = "Step Brothers"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Desc = "Mężczyzna zaczyna mówić 'tak' każdej propozycji.",
                            Director = "Peyton Reed",
                            Title = "Yes Man"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Desc = "Barwna opowieść o concierge'u i jego przygodach.",
                            Director = "Wes Anderson",
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Desc = "Historia przyjaźni i nadziei w więzieniu.",
                            Director = "Frank Darabont",
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Desc = "Niezwykłe życie prostolinijnego mężczyzny.",
                            Director = "Robert Zemeckis",
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Desc = "Nadzwyczajne wydarzenia w celi śmierci.",
                            Director = "Frank Darabont",
                            Title = "The Green Mile"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Desc = "Biografia genialnego matematyka zmagającego się z chorobą.",
                            Director = "Ron Howard",
                            Title = "A Beautiful Mind"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Desc = "Mężczyzna tworzy podziemny klub walki.",
                            Director = "David Fincher",
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Desc = "Ojciec walczy o lepsze życie dla syna.",
                            Director = "Gabriele Muccino",
                            Title = "The Pursuit of Happyness"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Desc = "Rzymski generał szuka zemsty jako gladiator.",
                            Director = "Ridley Scott",
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Desc = "Historia pianisty w czasie II wojny światowej.",
                            Director = "Roman Polanski",
                            Title = "The Pianist"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Desc = "Portret psychologiczny przyszłego przestępcy.",
                            Director = "Todd Phillips",
                            Title = "Joker"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Desc = "Student perkusji pod presją bezwzględnego nauczyciela.",
                            Director = "Damien Chazelle",
                            Title = "Whiplash"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Desc = "Pościg przez postapokaliptyczne pustkowia.",
                            Director = "George Miller",
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Desc = "Były zabójca wraca do świata przestępczego.",
                            Director = "Chad Stahelski",
                            Title = "John Wick"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Desc = "Policjant samotnie walczy z terrorystami.",
                            Director = "John McTiernan",
                            Title = "Die Hard"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Desc = "Batman staje do walki z Jokerem.",
                            Director = "Christopher Nolan",
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Desc = "Superbohaterowie łączą siły przeciw zagrożeniu.",
                            Director = "Joss Whedon",
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Desc = "Agent Ethan Hunt wykonuje kolejną niebezpieczną misję.",
                            Director = "Christopher McQuarrie",
                            Title = "Mission: Impossible – Fallout"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Desc = "James Bond rozpoczyna swoją służbę jako agent 007.",
                            Director = "Martin Campbell",
                            Title = "Casino Royale"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Desc = "Spektakularne walki na arenie starożytnego Rzymu.",
                            Director = "Ridley Scott",
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Desc = "Mężczyzna bez pamięci odkrywa, że jest wyszkolonym agentem.",
                            Director = "Doug Liman",
                            Title = "The Bourne Identity"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Desc = "Bitwa Spartan przeciwko perskiej armii.",
                            Director = "Zack Snyder",
                            Title = "300"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            Desc = "Zabawki ożywają pod nieobecność właściciela.",
                            Director = "John Lasseter",
                            Title = "Toy Story"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            Desc = "Młody lew walczy o swoje miejsce w królestwie.",
                            Director = "Roger Allers",
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            Desc = "Siostrzana miłość w magicznym królestwie.",
                            Director = "Chris Buck",
                            Title = "Frozen"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            Desc = "Ogr wyrusza na misję ratowania księżniczki.",
                            Director = "Andrew Adamson",
                            Title = "Shrek"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Desc = "Ojciec przemierza ocean w poszukiwaniu syna.",
                            Director = "Andrew Stanton",
                            Title = "Finding Nemo"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            Desc = "Staruszek wyrusza w podróż domu unoszącego się na balonach.",
                            Director = "Pete Docter",
                            Title = "Up"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            Desc = "Chłopiec odkrywa tajemnice przodków w świecie zmarłych.",
                            Director = "Lee Unkrich",
                            Title = "Coco"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            Desc = "Emocje sterują życiem dziewczynki.",
                            Director = "Pete Docter",
                            Title = "Inside Out"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            Desc = "Policyjna intryga w mieście zamieszkanym przez zwierzęta.",
                            Director = "Byron Howard",
                            Title = "Zootopia"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            Desc = "Dziewczynka trafia do magicznego świata duchów.",
                            Director = "Hayao Miyazaki",
                            Title = "Spirited Away"
                        });
                });

            modelBuilder.Entity("SklepSDUKW.Models.Film", b =>
                {
                    b.HasOne("SklepSDUKW.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SklepSDUKW.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
